server:
  port: 5052


dubbo:
  application:
    name: sea-provider-log
  registry:
    protocol: zookeeper
    address: 172.16.39.113:2181,172.16.39.114:2181,172.16.39.118:2181
  protocol:
    name: dubbo
    port: 20552
  version: 1.0.1
  scan:
    base-packages: com.log