server:
  port: 5051


dubbo:
  application:
    name: sea-consumer-web
  registry:
    protocol: zookeeper
    address: 172.16.39.113:2181,172.16.39.114:2181,172.16.39.118:2181
  protocol:
    name: dubbo
    port: 20551
  version: 1.0.0
  scan:
    base-packages: com.web
  consumer:
    timeout: 5000