server:
  port: 5053


dubbo:
  application:
    name: sea-provider-message
  registry:
    protocol: zookeeper
    address: 172.16.39.113:2181,172.16.39.114:2181,172.16.39.118:2181
  protocol:
    name: dubbo
    port: 20553
  version: 1.0.0
  scan:
    base-packages: com.message